apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: re4wf19a0-go 
  janus-idp.io/tekton: re4wf19a0-go
  backstage.io/kubernetes-id: re4wf19a0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: re4wf19a0-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml